### ISSUE TITLE
Bug with a sound between generation of tts and playing the tts

### ISSUE THREAD

**Issue by DickerSauerlaender** [Lordmau5/firebot-script-elevenlabs-tts#1]
![Bild_2023-12-13_202407421](https://github.com/Lordmau5/firebot-script-elevenlabs-tts/assets/62467817/b1d466e1-6989-44ae-a544-f7817182c83c)

Hey Lordmau5,

thanks for the cool script and your work.

Actually i have got the problem, that if i play a sound after the request before playing the tts, it plays no tts but generates it (i can see in the backend on elevenlabs):
![image](https://github.com/Lordmau5/firebot-script-elevenlabs-tts/assets/62467817/356b9dac-be78-49df-abc5-2443bbf7ef82)
![image](https://github.com/Lordmau5/firebot-script-elevenlabs-tts/assets/62467817/b59940fc-e84c-4723-a65a-924bcaca33d2)

If i delete the sound effect between, everything is working fine again.

**Comment by Lordmau5** [comment]
Hmm I tried replicating this in a test command just now.

- Request with text "This is a test message", and `Wait For Generation` ticked
- Play Sound with a ~7s audio, also `Wait for sound to finish` ticked
- Play TTS with the `$effectOutput`

Works fine on my end though :/

**Comment by DickerSauerlaender** [comment]
It just worked on the first time on my side. Then it stopped working again on the second, third, ... try.
![image](https://github.com/Lordmau5/firebot-script-elevenlabs-tts/assets/62467817/e0acbf09-a97d-4532-bb45-1433d180b2b6)

Then i deleted the "play sound" and retried. in this round it plays also all the not played tts from before.

**Comment by Lordmau5** [comment]
I think this is an issue in Firebot itself with the `Play Sound` effect.

I was able to reproduce this with 2 `Play Sound` effects in a row, the first one being set to `Wait for sound to finish`
With that, the 2nd sound doesn't play

**Comment by DickerSauerlaender** [comment]
@Lordmau5 thank you for the further investigations. Will you open up an issue?

**Comment by Lordmau5** [comment]
I brought it up to one of the devs in a DM, they're looking into it

It might be something that broke with the switch to Electron 27

**Comment by Lordmau5** [comment]
Okay, I was able to test a development build of Firebot that has this issue fixed, it should arrive with 5.59.2 or 5.60, though they don't know when that'll be

I'll keep the issue open in the meantime :)

**Comment by Lordmau5** [comment]
Oh, that was quick! https://github.com/crowbartools/Firebot/releases/tag/v5.59.2
